version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: urbanify_postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: urbanify
    ports:
      - "5432:5432"